### Test Base API
GET  http://localhost:8080


### Register new user
POST  http://localhost:8080/api/auth/signup
Content-Type: application/json

{"username": "jane", "password": "janejane"}


### Login
POST  http://localhost:8080/api/auth/signin
Content-Type: application/json

{"username": "ermal", "password": "ermalermal"}


### Get Public content
GET  http://localhost:8080/api/test/all


### Get private content for user with role USER
GET  http://localhost:8080/api/test/user
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyYTRjODJlMjc4YWU0YzRlMDE3NWJjZSIsImlhdCI6MTY1NDk3NTk3MCwiZXhwIjoxNjU1MDYyMzcwfQ.nRhnlHfMNIHWLVrBAfVL7pEEHDopJvm2o4KKSXATB2Y
#Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZC…DE0fQ.eeoQ9PM04V7pE5j6B3pZsqYCiGAzYtSYhaCVjVi72Z4


### Get private content for user with role Moderator
GET  http://localhost:8080/api/test/mod
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyYTRjODJlMjc4YWU0YzRlMDE3NWJjZSIsImlhdCI6MTY1NDk3NTk3MCwiZXhwIjoxNjU1MDYyMzcwfQ.nRhnlHfMNIHWLVrBAfVL7pEEHDopJvm2o4KKSXATB2Y


### Get private content for user with role Admin
GET  http://localhost:8080//api/test/admin
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyYTRjODJlMjc4YWU0YzRlMDE3NWJjZSIsImlhdCI6MTY1NDk3NTk3MCwiZXhwIjoxNjU1MDYyMzcwfQ.nRhnlHfMNIHWLVrBAfVL7pEEHDopJvm2o4KKSXATB2Y

