### Variables

@updatededCertification = {"name": "Oracle Professional", "url": "img/test.png"}

### Get All certifications
GET  http://localhost:8080/api/test/all

###
GET  http://localhost:8080/api/test/user
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyYTRjODJlMjc4YWU0YzRlMDE3NWJjZSIsImlhdCI6MTY1NDk3NTk3MCwiZXhwIjoxNjU1MDYyMzcwfQ.nRhnlHfMNIHWLVrBAfVL7pEEHDopJvm2o4KKSXATB2Y

###
GET  http://localhost:8080/api/test/mod
GET  http://localhost:8080/api/test/user
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyYTRjODJlMjc4YWU0YzRlMDE3NWJjZSIsImlhdCI6MTY1NDk3NTk3MCwiZXhwIjoxNjU1MDYyMzcwfQ.nRhnlHfMNIHWLVrBAfVL7pEEHDopJvm2o4KKSXATB2Y

###
GET  http://localhost:8080//api/test/admin
GET  http://localhost:8080/api/test/user
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyYTRjODJlMjc4YWU0YzRlMDE3NWJjZSIsImlhdCI6MTY1NDk3NTk3MCwiZXhwIjoxNjU1MDYyMzcwfQ.nRhnlHfMNIHWLVrBAfVL7pEEHDopJvm2o4KKSXATB2Y





